formal: Validate multiclock interface assumptions
openrisc/mor1kx pull request #132
Opened 2021-07-19 20:47 UTC by Harshitha172000

Multi clock interface had input assumptions that weren't verified
via CPU test. During the top module test, the pipeline_flush_i signal affects
input assumptions. So, modified the code to pass the test. CPU macro is used
to verify all input assumptions.

2021-07-19 23:42 UTC, stffrdhrn commented on bench/formal/mor1kx_cpu_cappuccino.sby
> +chparam -set FEATURE_MULTIPLIER "SERIAL" mor1kx_cpu_cappuccino
We will still only run for 5 clocks?

2021-07-19 23:44 UTC, stffrdhrn commented on bench/formal/f_multiclock_op.v
> +         if ($fell(f_op))
I don't eat too tech this after the fall, but always. Otherwise we get a pass if f_op_i is always high and the instruction runs forever.

2021-07-19 23:46 UTC, stffrdhrn commented on bench/formal/f_multiclock_op.v
> +            `ASSUME (!decode_valid_i);
I don't like mixing the decode valid assumptions into here. It makes it hard to understand.

2021-07-25 18:24 UTC, Harshitha172000 commented on bench/formal/mor1kx_execute_alu.sby
> +test_3stage_mul: depth 40
I think task `test_3stage_mul` requires more depth as it verifies the serial shifter.

2021-07-25 18:40 UTC, Harshitha172000 commented
Only the `OP_MAX_CLOCKS` assertion needs more depth in the top module test but not input assumption validation. I have verified all input assumptions with the added constraints and it passes the test.

2021-08-04 04:34 UTC, Harshitha172000 commented on rtl/verilog/mor1kx_execute_alu.v
> +             .f_op_i(op_ffl1_i),
I have used multi clock interface to check instructions l.ff1 or l.fl1. This check is applicable only to registered FFL1 as there is one clock cycle delay. For non-registered FFL1 implementation, the entire logic is driven by mux. So, not asserting it.

2021-08-05 01:13 UTC, stffrdhrn requested changes
Overall I think this is not adding much value to the original implementation.  Now that we are not enabling this for CPU level tests not much of the change is needed.

2021-08-05 01:13 UTC, stffrdhrn commented on bench/formal/f_multiclock_op.v
> +`endif
why do we do this only for ALU?

2021-08-05 01:13 UTC, stffrdhrn commented on bench/formal/f_multiclock_op.v
> +         end
Should we stop if valid or flush?

2021-08-05 01:13 UTC, stffrdhrn commented on rtl/verilog/mor1kx_execute_alu.v
> +             .f_op_i(op_ffl1_i),
ok

2021-08-05 05:56 UTC, Harshitha172000 commented on bench/formal/f_multiclock_op.v
> +         end
When we get valid, then the operation is completed, so stop counting. Ongoing op will be incomplete if `f_op_i` goes low in between; this happens when `pipeline_flush_i` arrives. Deasserting `f_op` enables us to start counting from zero when we get a new op, or else the count may increment from the old value.

2021-08-05 05:56 UTC, Harshitha172000 commented on bench/formal/f_multiclock_op.v
> +`endif
The proof will slow down if we set a depth of 40 for the CPU test.

2021-08-05 06:01 UTC, Harshitha172000 commented
> Overall I think this is not adding much value to the original implementation. Now that we are not enabling this for CPU level tests not much of the change is needed.

I just tried to validate input assumptions from the CPU's point of view. Now, I think it's not necessary to validate assumptions in the interface file. I will revert these changes.

2021-08-05 06:01 UTC, Harshitha172000 commented on bench/formal/f_multiclock_op.v
> +        assert ($past(alu_valid_o));
ok

2021-08-13 00:28 UTC, stffrdhrn commented on rtl/verilog/mor1kx_execute_alu.v
> +          op_mul_i & !op_ffl1_i) begin
Why do we need this `!op_ffl1_i` condition?  Shouldnt the op be part of the one hot assumption?

2021-08-13 00:29 UTC, stffrdhrn commented on rtl/verilog/mor1kx_execute_alu.v
> +             .f_stable_i({a, b, opc_alu_secondary_i}),
Why change from `rfa_i` to `a` (similar for `b`)?

2021-08-13 05:28 UTC, Harshitha172000 commented on rtl/verilog/mor1kx_execute_alu.v
> +          op_mul_i & !op_ffl1_i) begin
The one-hot assumption is not considered when reset is high, so this assertion fails when we simultaneously have `op_mul_i` and `op_ffl1_i` high. Anyhow, I will remove 'op_ffl1_i' here and modify one_hot.

2021-08-13 05:30 UTC, Harshitha172000 commented on rtl/verilog/mor1kx_execute_alu.v
> +             .f_stable_i({a, b, opc_alu_secondary_i}),
Because the number of shifts may be specified either through register or immediate.

2021-08-13 05:40 UTC, stffrdhrn commented on rtl/verilog/mor1kx_execute_alu.v
> +             .f_stable_i({a, b, opc_alu_secondary_i}),
I dont underrstand what you mean,  Can you change it back to `rfa_i, rfb_i, opc_alu_secondary_i`?  If you need other things to be stable you can add those as well.

2021-08-13 06:35 UTC, Harshitha172000 commented on rtl/verilog/mor1kx_execute_alu.v
> +             .f_stable_i({a, b, opc_alu_secondary_i}),
```if (CALCULATE_BRANCH_DEST=="TRUE") begin : calculate_branch_dest
   assign a = (op_jbr_i | op_jr_i) ? pc_execute_i : rfa_i;
   assign b = immediate_sel_i ? immediate_i :
              op_jbr_i ? {{4{immjbr_upper_i[9]}},immjbr_upper_i,imm16_i,2'b00} :
              rfb_i;
end else begin
   assign a = rfa_i;
   assign b = immediate_sel_i ? immediate_i : rfb_i;
```

Serial shifter shifts `a` by `b` number of bits. `b` value may be stored in the register, or it can be an immediate value.
Instead of including all immediate inputs `immjbr_upper_i, immediate_sel_i, immediate_i` , I kept `b` stable.

2021-08-13 06:43 UTC, Harshitha172000 commented on bench/formal/mor1kx_execute_alu.sby
> +test_3stage_mul: depth 40
Fine. I will add a barrel shifter for `test_3stage_mul`

2021-08-14 22:36 UTC, stffrdhrn approved these changes

2021-08-14 22:38 UTC, merged